#!/bin/bash

# PINK MIDDLE BAR
#COLOR_SPACE_BG=$COLOR_DRACULA_BUFFY #$COLOR_DRACULA_LINCOLN
COLOR_UTILS_BG=0xffa53e8f
COLOR_SPACE_SELECTED_SPACE_NO_BG=$COLOR_DRACULA_BUFFY
COLOR_SPACE_SELECTED_ICON=$COLOR_DRACULA_BUFFY #0xfff8f8f2
COLOR_SPACE_SELECTED_BG=$COLOR_UTILS_BG