#!/bin/bash
source "$HOME/.config/sketchybar/utils.sh"

LAYOUTS="$HOME/.config/sketchybar/layouts"
CONFIG_DIR="$HOME/.config/sketchybar"
DISPLAY_NUMBER=3

# Get the display type of the secondary display
DISPLAY_TYPE=$(get_display_type $DISPLAY_NUMBER)
echo "Display 3 is of type '$DISPLAY_TYPE'."

# Check if the secondary display type is "Built-in"
if [[ $DISPLAY_TYPE = "Built-in"* ]]; then
	source "$LAYOUTS/laptop.sh"
else
	source "$LAYOUTS/desktop-rounded.sh"
fi