#!/bin/bash
source "$HOME/.config/sketchybar/utils.sh"

SKETCHYBAR_CONFIG="$HOME/.config/sketchybar"
CONFIG_DIR="$HOME/.config/sketchybar"
DISPLAY_NUMBER=3

# Get the display type of the secondary display
DISPLAY_TYPE=$(get_display_type $DISPLAY_NUMBER)
echo "Display 3 is of type '$DISPLAY_TYPE'."

# Check if the secondary display type is "Built-in"
if [[ $DISPLAY_TYPE = "Built-in"* ]]; then
	echo "Display number $DISPLAY_NUMBER is of type 'Built-in'. Loading laptop configuration."
	source "$SKETCHYBAR_CONFIG/sketchybarrc-laptop"
else
	echo "Display number $DISPLAY_NUMBER is not of type 'Built-in'. Loading desktop configuration."
	source "$SKETCHYBAR_CONFIG/sketchybarrc-desktop"
fi