#!/bin/bash

# General Icons
ICON_LOADING=􀖇
ICON_APPLE=
ICON_PREFERENCES=􀺽
ICON_ACTIVITY=􀒓
ICON_LOCK=􀒳
ICON_BELL=􀋚
ICON_BELL_DOT=􀝗

# Separators
ICON_SEPARATOR_RIGHT=
ICON_SEPARATOR_LEFT=

# Git Icons
ICON_GIT_ISSUE=􀍷
ICON_GIT_DISCUSSION=􀒤
ICON_GIT_PULL_REQUEST=􀙡
ICON_GIT_COMMIT=􀡚
ICON_GIT_INDICATOR=􀂓

# Spotify Icons
ICON_SPOTIFY=
ICON_SPOTIFY_PAUSE= #
ICON_SPOTIFY_PLAY= #

# Yabai Icons
ICON_YABAI_STACK=􀏭
ICON_YABAI_FULLSCREEN_ZOOM=􀏜
ICON_YABAI_PARENT_ZOOM=􀥃
ICON_YABAI_FLOAT=􀢌
ICON_YABAI_GRID=􀧍

# CPU Icons
ICON_CPU=􀧓

# Battery Icons
ICON_BATTERY_100=􀛨
ICON_BATTERY_75=􀺸
ICON_BATTERY_50=􀺶
ICON_BATTERY_25=􀛩
ICON_BATTERY_0=􀛪
ICON_BATTERY_CHARGING=􀢋

# Volume Icons
ICON_VOLUME=􀊉

ICON_VOLUME_100=􀊩
ICON_VOLUME_66=􀊧
ICON_VOLUME_33=􀊥
ICON_VOLUME_10=􀊡
ICON_VOLUME_0=􀊣

# WiFi
ICON_WIFI_CONNECTED=􀙇
ICON_WIFI_DISCONNECTED=􀙈

# Brew
ICON_BREW=􀐛
ICON_BREW_UPDATED=􀆅