#!/bin/bash
# https://www.nerdfonts.com/cheat-sheet


# General Icons
ICON_LOADING=􀖇
ICON_APPLE=
ICON_PREFERENCES=􀺽
ICON_ACTIVITY=􀒓
ICON_LOCK=􀒳
ICON_BELL=􀋚
ICON_BELL_DOT=􀝗

# Separators
ICON_SEPARATOR_RIGHT=
ICON_SEPARATOR_LEFT=

# Git Icons
ICON_GIT_ISSUE=􀍷
ICON_GIT_DISCUSSION=􀒤
ICON_GIT_PULL_REQUEST=􀙡
ICON_GIT_COMMIT=􀡚
ICON_GIT_INDICATOR=􀂓

# Spotify Icons
ICON_SPOTIFY=
ICON_SPOTIFY_PAUSE= #
ICON_SPOTIFY_PLAY= #

# Yabai Icons
ICON_YABAI_STACK=􀏭
ICON_YABAI_FULLSCREEN_ZOOM=􀏜
ICON_YABAI_PARENT_ZOOM=􀥃
ICON_YABAI_FLOAT=􀢌
ICON_YABAI_GRID=􀧍

# CPU Icons
ICON_CPU=
ICON_CPU_USER= #󰣆 # #
ICON_CPU_SYS=

ICON_CPU_IDLE=󰌪
ICON_CPU_LOAD_1=$ICON_CPU_IDLE #󱤅 #󰄴 #󰗡 #󰄰
ICON_CPU_LOAD_2=󰪞
ICON_CPU_LOAD_3=󰪟
ICON_CPU_LOAD_4=󰪠
ICON_CPU_LOAD_5=󰪡
ICON_CPU_LOAD_6=󰪢
ICON_CPU_LOAD_7=󰪣
ICON_CPU_LOAD_8=󰪤
ICON_CPU_LOAD_9=󰪥
ICON_CPU_LOAD_10=󰀨 #󱠇 #󰄯
#ICON_CPU_LOAD_11=

# Battery Icons
ICON_BATTERY_100=
ICON_BATTERY_75=
ICON_BATTERY_50=
ICON_BATTERY_25=
ICON_BATTERY_0=
ICON_BATTERY_CHARGING=􀢋

# Battery Icons Vertical
ICON_BATTERY_UNKNOWN=󰂑

ICON_BATTERY_V100=󰁹
ICON_BATTERY_V90=󰂂
ICON_BATTERY_V80=󰂁
ICON_BATTERY_V70=󰂀
ICON_BATTERY_V60=󰁿
ICON_BATTERY_V50=󰁾
ICON_BATTERY_V40=󰁽
ICON_BATTERY_V30=󰁼
ICON_BATTERY_V20=󰁻
ICON_BATTERY_V10=󰁺
ICON_BATTERY_V0=󰂎

ICON_BATTERY_CH_V100=󰂅
ICON_BATTERY_CH_V90=󰂋
ICON_BATTERY_CH_V80=󰂊
ICON_BATTERY_CH_V70=󰢞
ICON_BATTERY_CH_V60=󰂉
ICON_BATTERY_CH_V50=󰢝
ICON_BATTERY_CH_V40=󰂈
ICON_BATTERY_CH_V30=󰂇
ICON_BATTERY_CH_V20=󰂆
ICON_BATTERY_CH_V10=󰢜
ICON_BATTERY_CH_V0=󰢟


# Volume Icons
ICON_VOLUME=󰖁

ICON_VOLUME_100=􀊩
ICON_VOLUME_66=􀊧
ICON_VOLUME_33=􀊥
ICON_VOLUME_10=􀊡
ICON_VOLUME_0=􀊣

# WiFi
ICON_WIFI_CONNECTED=􀙇
ICON_WIFI_DISCONNECTED=􀙈

# Brew
ICON_BREW=􀐛
ICON_BREW_UPDATED=􀆅

# Docker
ICON_DOCKER=

# Airpods
ICON_AIRPODS=󰋋
ICON_AIRPODS_CASE=󰋌