#!/usr/bin/env zsh

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

FONT_FACE="JetBrainsMono Nerd Font"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$CONFIG_DIR/items"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"


# Get the screen resolution
#SCREEN_RESOLUTION=$(system_profiler SPDisplaysDataType | awk '/Resolution/{print $2, $4}' | head -n1)
# Extract the width from the resolution
#SCREEN_WIDTH=$(echo $SCREEN_RESOLUTION | awk '{print $1}')
# Calculate 10% of the screen width
#SCREEN_WIDTH_PERCENT=$(echo "$SCREEN_WIDTH * 0.10" | bc -l)
# Round the result to an integer, as screen dimensions should be whole numbers
#SCREEN_WIDTH_PERCENT=$(printf "%.0f" $SCREEN_WIDTH_PERCENT)
# If the number is odd, subtract 1 to make it even
#if [ $(($SCREEN_WIDTH_PERCENT % 2)) -ne 0 ]; then
#    SCREEN_WIDTH_PERCENT=$(($SCREEN_WIDTH_PERCENT - 1))
#fi

# Debug output
#echo "Screen resolution: $SCREEN_RESOLUTION" >> ~/sketchybar_debug.log
#echo "Screen width: $SCREEN_WIDTH" >> ~/sketchybar_debug.log
#echo "20% of screen width: $SCREEN_WIDTH_PERCENT" >> ~/sketchybar_debug.log

BAR_HEIGHT=24
MARGIN_LEFT=300
MARGIN_RIGHT=300
SEPARATOR_WIDTH=100
DEFAULT_PADDING=10


FRONT_APP_ICON_SIZE=16
FRONT_APP_NAME_SIZE=16

# ------------------------
# MAIN BAR
# ------------------------

sketchybar \
    --bar \
        height=$BAR_HEIGHT \
        color=$COLOR_BAR \
        margin=0 \
        sticky=on \
        padding_left=0 \
        padding_right=0 \
        display=main

sketchybar \
    --default \
        background.height=$BAR_HEIGHT \
        icon.color=$COLOR_TEXT \
        icon.font="$FONT_FACE:Medium:16.0" \
        icon.padding_left=5 \
        icon.padding_right=5 \
        label.color=$COLOR_TEXT \
        label.font="$FONT_FACE:Bold:14.0" \
        label.y_offset=1 \
        label.padding_left=0 \
        label.padding_right=5

# ------------------------
# LEFT
# ------------------------

# -- SEPARATOR --

sketchybar --add item separator_1 left \
           --set separator_1 \
                 background.color=$COLOR_SECONDARY \
                 icon.padding_right=$SEPARATOR_WIDTH

source $ITEM_DIR/spaces.sh

# -- SEPARATOR --

sketchybar --add item separator_2 left \
           --set separator_2 \
                      background.color=$COLOR_SECONDARY \
                      icon.padding_right=$SEPARATOR_WIDTH
              

# -- ACTIVE SPACE & ACTIVE WINDOW --

sketchybar \
    --add item current_space.separator left \
    --set current_space.separator \
            icon= \
            icon.color=$COLOR_SECONDARY \
            background.color=$COLOR_ACCENT \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=0 \
            icon.padding_right=-8 \
            icon.y_offset=1

source $ITEM_DIR/front_app_icon.sh

sketchybar \
    --add item front_app.separator left \
    --set front_app.separator \
            background.color=0x00000000 \
            icon= \
            icon.color=$COLOR_ACCENT \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=0 \
            icon.padding_right=0 \
            icon.y_offset=1 \
            label.drawing=no

source $ITEM_DIR/front_app_name.sh


# -- FRONT APPLICATION --

sketchybar \
    --add bracket front_app_bracket \
            front_app \
            front_app.separator \
            front_app.name \
    --subscribe front_app front_app_switched mouse.clicked

# ------------------------
# MIDDLE
# ------------------------

source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/memory.sh
source $ITEM_DIR/volume.sh

# ------------------------
# RIGHT
# ------------------------

# -- SEPARATOR --

sketchybar --add item separator_3 right \
           --set separator_3 \
                      background.color=$COLOR_SECONDARY \
                      icon.padding_right=$SEPARATOR_WIDTH

source $ITEM_DIR/clock.sh

# -- SEPARATOR --

sketchybar --add item separator_4 right \
           --set separator_4 \
                      background.color=$COLOR_SECONDARY \
                      icon.padding_right=$SEPARATOR_WIDTH

sketchybar \
    --add item clock.separator right \
    --set clock.separator \
            background.color=$COLOR_ACCENT \
            icon= \
            icon.color=$COLOR_SECONDARY \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=0 \
            icon.padding_right=-8 \
            icon.y_offset=1

source $ITEM_DIR/spotify.sh

sketchybar \
    --add item spotify.separator right \
    --set spotify.separator \
            icon= \
            icon.color=$COLOR_ACCENT \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=0 \
            icon.padding_right=-8 \
            icon.y_offset=1


# ------------------------
# INIT
# ------------------------

sketchybar --update
sketchybar --trigger space_change
sketchybar --trigger volume_change