#!/usr/bin/env zsh
source "$CONFIG_DIR/colors.sh" # Loads all defined colors

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=38 \
    color=$BAR_COLOR \
    margin=0 \
    sticky=on \
    padding_left=0 \
    padding_right=0 \
    notch_width=240 \
    display=main

sketchybar --default \
    background.height=24 \
    icon.color=$TEXT_COLOR \
    icon.font="$FONT_FACE:Medium:16.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.color=$TEXT_COLOR \
    label.font="$FONT_FACE:Bold:14.0" \
    label.y_offset=1 \
    label.padding_left=0 \
    label.padding_right=5

sketchybar --add item current_space left \
    --set current_space \
    icon.color=$SPACE_FONT_COLOR \
    background.color=$SECONDARY_COLOR \
    label.drawing=off \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

sketchybar --add item front_app left \
    --set front_app \
    background.color=$ACCENT_COLOR \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.font="sketchybar-app-font:Regular:16.0" \
    icon.padding_right=10 \
    icon.padding_left=10 \
    icon.y_offset=1 \
    label.drawing=no \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    icon= \
    icon.color=$ACCENT_COLOR \
    icon.font="$FONT_FACE:Bold:23.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:16.0" \
    label.color=0xffcad3f5 \
    label.padding_left=10

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify e \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    icon.font="$FONT_FACE:Bold:20.0" \
    label.drawing=off \
    label.padding_left=3 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

sketchybar --add item current_space left \
    --set current_space \
    background.color=$SECONDARY_COLOR \
    icon.color=0xff24273a \
    label.drawing=off \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

sketchybar --add item front_app left \
    --set front_app \
    background.color=$ACCENT_COLOR \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.font="sketchybar-app-font:Regular:15.0" \
    icon.padding_right=10 \
    icon.padding_left=10 \
    icon.y_offset=0 \
    label.drawing=no \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    icon= \
    icon.color=$ACCENT_COLOR \
    icon.font="$FONT_FACE:Bold:18.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:16.0" \
    label.color=0xffcad3f5 \
    label.padding_left=10

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item weather.moon q \
    --set weather.moon \
    background.color=0x667dc4e4 \
    background.padding_right=-1 \
    icon.color=0xff181926 \
    icon.font="$FONT_FACE:Bold:22.0" \
    icon.padding_left=4 \
    icon.padding_right=3 \
    label.drawing=off \
    --subscribe weather.moon mouse.clicked

sketchybar --add item weather q \
    --set weather \
    icon= \
    icon.color=0xfff5bde6 \
    icon.font="$FONT_FACE:Bold:15.0" \
    update_freq=1800 \
    script="$PLUGIN_SHARED_DIR/weather.sh" \
    --subscribe weather system_woke

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=0xffed8796 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh" 

sketchybar --add item battery right \
    --set battery \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
    --set volume \
    icon.color=0xff8aadf4 \
    label.drawing=true \
    script="$PLUGIN_SHARED_DIR/volume.sh" \
    --subscribe volume volume_change

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
sketchybar --trigger volume_change