#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors

FONT_FACE="JetBrainsMono Nerd Font"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$HOME/.config/sketchybar/items"

BAR_HEIGHT=24
MARGIN_LEFT=20
MARGIN_RIGHT=20
SEPARATOR_WIDTH=100
DEFAULT_PADDING=10

FRONT_APP_ICON_SIZE=16
FRONT_APP_NAME_SIZE=16

# ------------------------
# MAIN BAR
# ------------------------

$BAR_NAME \
    --bar \
        height=$BAR_HEIGHT \
        color=$COLOR_BAR \
        margin=0 \
        sticky=on \
        padding_left=0 \
        padding_right=0 \
        display=2

$BAR_NAME \
    --default \
        background.height=$BAR_HEIGHT \
        icon.color=$COLOR_TEXT \
        icon.font="$FONT_FACE:Medium:16.0" \
        icon.padding_left=5 \
        icon.padding_right=5 \
        label.color=$COLOR_TEXT \
        label.font="$FONT_FACE:Bold:14.0" \
        label.y_offset=1 \
        label.padding_left=0 \
        label.padding_right=5

# ------------------------
# LEFT
# ------------------------

# -- SEPARATOR --

$BAR_NAME --add item separator_1 left \
           --set separator_1 \
                 background.color=$COLOR_SECONDARY \
                 icon.padding_right=20

source $ITEM_DIR/spaces.sh

# -- SEPARATOR --

$BAR_NAME --add item separator_2 left \
           --set separator_2 \
                 background.color=$COLOR_SECONDARY \
                 icon.padding_right=20

# -- ACTIVE SPACE & ACTIVE WINDOW --

$BAR_NAME \
    --add item current_space.separator left \
    --set current_space.separator \
            icon= \
            icon.color=$COLOR_SECONDARY \
            background.color=$COLOR_ACCENT \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=0 \
            icon.padding_right=-8 \
            icon.y_offset=1

source $ITEM_DIR/front_app_icon.sh

$BAR_NAME \
    --add item front_app.separator left \
    --set front_app.separator \
            background.color=0x00000000 \
            icon= \
            icon.color=$COLOR_ACCENT \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=0 \
            icon.padding_right=0 \
            icon.y_offset=1 \
            label.drawing=no

source $ITEM_DIR/front_app_name.sh

# -- FRONT APPLICATION --

$BAR_NAME \
    --add bracket front_app_bracket \
            front_app \
            front_app.separator \
            front_app.name \
    --subscribe front_app front_app_switched mouse.clicked

# ------------------------
# INIT
# ------------------------

$BAR_NAME --update
$BAR_NAME --trigger space_change
$BAR_NAME --trigger volume_change