#!/usr/bin/env zsh

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

FONT_FACE="JetBrainsMono Nerd Font"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"
SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

MARGIN_LEFT=20
MARGIN_RIGHT=20
BAR_HEIGHT=32

# ------------------------
# LEFT
# ------------------------

sketchybar \
    --bar \
        height=$BAR_HEIGHT \
        color=$COLOR_BAR \
        margin=0 \
        sticky=on \
        padding_left=0 \
        padding_right=0 \
        notch_width=200 \
        display=main

sketchybar \
    --default \
        background.height=$BAR_HEIGHT \
        icon.color=$COLOR_TEXT \
        icon.font="$FONT_FACE:Medium:19.0" \
        icon.padding_left=5 \
        icon.padding_right=5 \
        label.color=$COLOR_TEXT \
        label.font="$FONT_FACE:Bold:13.0" \
        label.y_offset=1 \
        label.padding_left=5 \
        label.padding_right=5

sketchybar \
    --add item current_space left \
    --set current_space \
            icon.padding_left=$MARGIN_LEFT \
            icon.padding_right=10 \
            icon.color=$COLOR_TEXT_CONTRAST \
            background.color=$COLOR_SECONDARY \
            label.drawing=off \
            script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

sketchybar \
    --add item front_app left \
    --set front_app \
            background.color=$COLOR_ACCENT \
            background.padding_left=0 \
            background.padding_right=0 \
            icon.font="sketchybar-app-font:Regular:20.0" \
            icon.padding_right=10 \
            icon.padding_left=10 \
            icon.y_offset=0 \
            label.drawing=no \
            script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
            background.color=0x00000000 \
            icon= \
            icon.color=$COLOR_ACCENT \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=0 \
            icon.padding_right=0 \
            icon.y_offset=1 \
            label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
            background.color=0x00000000 \
            icon.drawing=off \
            label.font="$FONT_FACE:Bold:20.0" \
            label.color=0xffcad3f5 \
            label.padding_left=20

sketchybar \
    --add bracket front_app_bracket \
        front_app \
        front_app.separator \
        front_app.name \
    --subscribe front_app front_app_switched mouse.clicked
    
# ------------------------
# CENTER
# ------------------------

sketchybar \
    --add item volume e \
    --set volume \
        icon.padding_left=10 \
        label.padding_right=10 \
        label.drawing=true \
        script="$PLUGIN_SHARED_DIR/volume.sh" \
    --subscribe volume volume_change

sketchybar \
    --add item battery q \
    --set battery \
        update_freq=20 \
        script="$PLUGIN_SHARED_DIR/battery.sh"

sketchybar --add item cpu q \
           --set cpu  update_freq=5 \
                      icon.padding_left=10 \
                      label.padding_right=10 \
                      icon=􀧓 \
                      script="$PLUGIN_SHARED_DIR/cpu.sh"

sketchybar --add item memory q \
    --set memory \
        icon=  \
        icon.padding_left=10 \
        label.padding_right=10 \
        update_freq=10 \
        script="$PLUGIN_SHARED_DIR/memory.sh"

# ------------------------
# RIGHT
# ------------------------

sketchybar \
    --add item clock right \
    --set clock \
            icon.padding_left=0 \
            label.padding_left=0 \
            label.color=$COLOR_TEXT_CONTRAST \
            label.padding_right=$MARGIN_RIGHT \
            background.color=$COLOR_SECONDARY \
            update_freq=10 \
            script="$PLUGIN_SHARED_DIR/clock.sh" \
    --add item clock.separator right \
    --set clock.separator \
            background.color=$COLOR_ACCENT \
            icon= \
            icon.color=$COLOR_SECONDARY \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=5 \
            icon.padding_right=-12 \
            icon.y_offset=1

sketchybar \
    --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify right \
    --set spotify \
            icon= \
            icon.y_offset=0 \
            icon.padding_left=10 \
            icon.padding_right=10 \
            label.padding_right=10 \
            label.padding_left=0 \
            label.drawing=off \
            background.color=$COLOR_ACCENT \
            script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked \
    --add item spotify.separator right \
    --set spotify.separator \
            icon= \
            icon.color=$COLOR_ACCENT \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=0 \
            icon.padding_right=-12 \
            icon.y_offset=1

# ------------------------
# INIT
# ------------------------
sketchybar --update
sketchybar --trigger space_change
sketchybar --trigger volume_change
sketchybar --trigger spotify_change