#!/bin/bash
source "$CONFIG_DIR/colors.sh" # Loads all defined colors

FONT_FACE="JetBrainsMono Nerd Font"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$CONFIG_DIR/items"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"


# Get the screen resolution
#SCREEN_RESOLUTION=$(system_profiler SPDisplaysDataType | awk '/Resolution/{print $2, $4}' | head -n1)
# Extract the width from the resolution
#SCREEN_WIDTH=$(echo $SCREEN_RESOLUTION | awk '{print $1}')
# Calculate 10% of the screen width
#SCREEN_WIDTH_PERCENT=$(echo "$SCREEN_WIDTH * 0.10" | bc -l)
# Round the result to an integer, as screen dimensions should be whole numbers
#SCREEN_WIDTH_PERCENT=$(printf "%.0f" $SCREEN_WIDTH_PERCENT)
# If the number is odd, subtract 1 to make it even
#if [ $(($SCREEN_WIDTH_PERCENT % 2)) -ne 0 ]; then
#    SCREEN_WIDTH_PERCENT=$(($SCREEN_WIDTH_PERCENT - 1))
#fi

# Debug output
#echo "Screen resolution: $SCREEN_RESOLUTION" >> ~/sketchybar_debug.log
#echo "Screen width: $SCREEN_WIDTH" >> ~/sketchybar_debug.log
#echo "20% of screen width: $SCREEN_WIDTH_PERCENT" >> ~/sketchybar_debug.log

BAR_HEIGHT=22
SEPARATOR_WIDTH=20
DEFAULT_PADDING=10


FRONT_APP_ICON_SIZE=14
FRONT_APP_NAME_SIZE=15

# ------------------------
# MAIN BAR
# ------------------------

$BAR_NAME \
    --bar \
        height=$BAR_HEIGHT \
        color=$COLOR_BAR \
        margin=0 \
        sticky=on \
        padding_left=0 \
        padding_right=0 \
        display=main \
    --default \
        background.height=$BAR_HEIGHT \
        icon.color=$COLOR_TEXT \
        icon.font="$FONT_FACE:Medium:16.0" \
        icon.padding_left=5 \
        icon.padding_right=5 \
        label.color=$COLOR_TEXT \
        label.font="$FONT_FACE:Bold:14.0" \
        label.y_offset=1 \
        label.padding_left=0 \
        label.padding_right=5

# ------------------------
# LEFT
# ------------------------
#󰑓
$BAR_NAME \
    --add item reload left \
    --set reload \
            icon= \
            icon.color=$COLOR_RELOAD_ICON \
            icon.padding_left=10 \
            icon.padding_right=5 \
            background.color=$COLOR_RELOAD_BG \
            label.padding_right=0 \
            label.padding_right=0 \
            script="$PLUGIN_SHARED_DIR/reload.sh" \
    --subscribe reload mouse.clicked mouse.entered mouse.exited \
    --add item reload.separator left \
    --set reload.separator \
            icon= \
            icon.color=$COLOR_RELOAD_BG \
            background.color=$COLOR_SPACE_BG \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=0 \
            icon.padding_right=0 \
            icon.y_offset=1
            
source $ITEM_DIR/spaces.sh

# -- SEPARATOR --

#$BAR_NAME \
#     --add item separator_2 left \
#     --set separator_2 \
#             background.color=$COLOR_SPACE_BG \
#             icon.padding_right=$SEPARATOR_WIDTH

# -- ACTIVE SPACE & ACTIVE WINDOW --

$BAR_NAME \
    --add item current_space.separator left \
    --set current_space.separator \
            icon= \
            icon.color=$COLOR_SPACE_BG \
            background.color=$COLOR_FRONT_APP_ICON_BG \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=0 \
            icon.padding_right=-8 \
            icon.y_offset=1

source $ITEM_DIR/front_app_icon.sh
source $ITEM_DIR/front_app_name.sh

$BAR_NAME \
    --add item front_app.separator left \
    --set front_app.separator \
            background.color=0x00000000 \
            icon= \
            icon.color=$COLOR_FRONT_APP_ICON_BG \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=0 \
            icon.padding_right=0 \
            icon.y_offset=1 \
            label.drawing=no

# -- FRONT APPLICATION --

$BAR_NAME \
    --add bracket front_app_bracket \
            front_app \
            front_app.separator \
            front_app.name \
    --subscribe front_app front_app_switched mouse.clicked

# ------------------------
# MIDDLE
# ------------------------


# ------------------------
# RIGHT
# ------------------------

# -- SEPARATOR --

$BAR_NAME \
    --add item separator_3 right \
    --set separator_3 \
            icon.padding_right=$SEPARATOR_WIDTH \
    --add item clock right \
    --set clock \
            label.color=$COLOR_RIGHT_AREA_TEXT \
            update_freq=10 \
            script="$PLUGIN_SHARED_DIR/clock.sh" \
    --add item separator_5 right \
    --set separator_5 \
            icon.padding_right=$SEPARATOR_WIDTH \
    --add item battery right \
    --set battery \
            update_freq=20 \
            icon.padding_left=10 \
            label.padding_right=10 \
            label.width=38 \
            label.color=$COLOR_RIGHT_AREA_TEXT \
            icon.color=$COLOR_RIGHT_AREA_TEXT \
            script="$PLUGIN_SHARED_DIR/battery.sh" \
    --add item cpu right \
    --set cpu update_freq=5 \
            icon.padding_left=10 \
            label.padding_right=10 \
            label.width=38 \
            icon=􀧓 \
            label.color=$COLOR_RIGHT_AREA_TEXT \
            icon.color=$COLOR_RIGHT_AREA_TEXT \
            script="$PLUGIN_SHARED_DIR/cpu.sh" \
    --add item volume right \
    --set volume \
            icon.padding_left=10 \
            label.padding_right=10 \
            label.width=38 \
            label.drawing=true \
            label.color=$COLOR_RIGHT_AREA_TEXT \
            icon.color=$COLOR_RIGHT_AREA_TEXT \
            script="$PLUGIN_SHARED_DIR/volume.sh" \
    --subscribe volume volume_change \
    --add item separator_4 right \
    --set separator_4 \
                icon.padding_right=0 \
    --add bracket right_area \
            separator_3 \
            clock \
            separator_4 \
            separator_5 \
            battery \
            cpu \
            volume \
     --set right_area \
            background.color=$COLOR_RIGHT_AREA_BG

# -- SEPARATOR --

$BAR_NAME \
        --add item clock.separator right \
        --set clock.separator \
                background.color=$COLOR_ACCENT \
                icon= \
                icon.color=$COLOR_RIGHT_AREA_BG \
                icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
                icon.padding_left=0 \
                icon.padding_right=-8 \
                icon.y_offset=1 \
        --add event spotify_change $SPOTIFY_EVENT \
        --add item spotify right \
        --set spotify \
                icon= \
                icon.y_offset=1 \
                icon.padding_left=10 \
                icon.padding_right=10 \
                label.padding_right=10 \
                label.drawing=off \
                label.padding_left=3 \
                background.color=$COLOR_ACCENT \
                script="$PLUGIN_DIR/spotify.sh" \
        --subscribe spotify spotify_change mouse.clicked \
        --add item spotify.separator right \
        --set spotify.separator \
                icon= \
                icon.color=$COLOR_ACCENT \
                icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
                icon.padding_left=0 \
                icon.padding_right=-8 \
                icon.y_offset=1

# ------------------------
# INIT
# ------------------------

$BAR_NAME --update
$BAR_NAME --trigger space_change
$BAR_NAME --trigger volume_change
$BAR_NAME --trigger display_change