#!/usr/bin/env zsh

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

FONT_FACE="JetBrainsMono Nerd Font"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"
ITEM_DIR="$CONFIG_DIR/items"
SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

MARGIN_LEFT=20
MARGIN_RIGHT=20
BAR_HEIGHT=32
SEPARATOR_WIDTH=20

FRONT_APP_ICON_SIZE=20
FRONT_APP_NAME_SIZE=20


sketchybar \
    --bar \
        height=$BAR_HEIGHT \
        color=$COLOR_BAR \
        margin=0 \
        sticky=on \
        padding_left=0 \
        padding_right=0 \
        notch_width=200 \
        display=main

sketchybar \
    --default \
        background.height=$BAR_HEIGHT \
        icon.color=$COLOR_TEXT \
        icon.font="$FONT_FACE:Medium:19.0" \
        icon.padding_left=5 \
        icon.padding_right=5 \
        label.color=$COLOR_TEXT \
        label.font="$FONT_FACE:Bold:13.0" \
        label.y_offset=1 \
        label.padding_left=5 \
        label.padding_right=5

# ------------------------
# LEFT
# ------------------------

sketchybar --add item separator_1 left \
           --set separator_1 \
                 background.color=$COLOR_SECONDARY \
                 icon.padding_right=$MARGIN_LEFT

source $ITEM_DIR/current_space_no.sh
source $ITEM_DIR/front_app_icon.sh

sketchybar \
    --add item front_app.separator left \
    --set front_app.separator \
            background.color=0x00000000 \
            icon= \
            icon.color=$COLOR_ACCENT \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=0 \
            icon.padding_right=0 \
            icon.y_offset=1 \
            label.drawing=no

source $ITEM_DIR/front_app_name.sh

sketchybar \
    --add bracket front_app_bracket \
        front_app \
        front_app.separator \
        front_app.name \
    --subscribe front_app front_app_switched mouse.clicked
    
# ------------------------
# CENTER
# ------------------------

source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/memory.sh
source $ITEM_DIR/volume.sh

# ------------------------
# RIGHT
# ------------------------

sketchybar --add item separator_3 right \
           --set separator_3 \
                      background.color=$COLOR_SECONDARY \
                      icon.padding_right=$SEPARATOR_WIDTH

source $ITEM_DIR/clock.sh

sketchybar \
    --add item clock.separator right \
    --set clock.separator \
            background.color=$COLOR_ACCENT \
            icon= \
            icon.color=$COLOR_SECONDARY \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=5 \
            icon.padding_right=-12 \
            icon.y_offset=1

source $ITEM_DIR/spotify.sh

sketchybar \
    --add item spotify.separator right \
    --set spotify.separator \
            icon= \
            icon.color=$COLOR_ACCENT \
            icon.font="$FONT_FACE:Bold:$BAR_HEIGHT.0" \
            icon.padding_left=0 \
            icon.padding_right=-12 \
            icon.y_offset=1

# ------------------------
# INIT
# ------------------------
sketchybar --update
sketchybar --trigger space_change
sketchybar --trigger volume_change
sketchybar --trigger spotify_change