#!/bin/bash

SKETCHYBAR_CONFIG="$HOME/.config/sketchybar"
export DISPLAY_NUMBER=1

# Determines if a monitor is used
# Since the notch is -only- on the laptop, if a monitor isn't used,
# then that means the internal display is used ¯\_(ツ)_/¯
MAIN_DISPLAY=$(system_profiler SPDisplaysDataType | grep -B 3 'Main Display:' | awk '/Display Type/ {print $3}')

# Check if the display type is "Built-in"
if [[ $MAIN_DISPLAY = "Built-in" ]]; then
	echo "Display number $DISPLAY_NUMBER is of type 'Built-in'. Loading laptop configuration."
	source "$SKETCHYBAR_CONFIG/sketchybarrc-laptop"
else
	echo "Display number $DISPLAY_NUMBER is not of type 'Built-in'. Loading desktop configuration."
	source "$SKETCHYBAR_CONFIG/sketchybarrc-desktop"
fi