#!/bin/bash

# MAGENTA MIDDLE BAR
#COLOR_SPACE_BG=$COLOR_DRACULA_MAGENTA_1 #$COLOR_DRACULA_LINCOLN

COLOR_A=0xff8aadf5
COLOR_B=0xff4a5d84

#COLOR_SPACE_BG=$COLOR_DRACULA_BUFFY #$COLOR_DRACULA_LINCOLN
COLOR_UTILS_BG=$COLOR_B
COLOR_SPACE_SELECTED_SPACE_NO_BG=$COLOR_A
COLOR_SPACE_SELECTED_ICON=$COLOR_A #0xfff8f8f2
COLOR_SPACE_SELECTED_BG=$COLOR_UTILS_BG