#!/bin/bash

#borders active_color=0x88f8f8f2 inactive_color=0x44000000 width=8.0 hidpi=off & #blur_radius=4.0
options=(
	style=round
	width=8.0
	hidpi=off
	active_color=0x88f8f8f2
	inactive_color=0x44000000
)

borders "${options[@]}"